Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('Profile.urls')), 
    path('resume/', include('Resume.urls')),
    path('projects/', include('Projects.urls')),
    path('skills/', include('Skills.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Resume/urls.py
from django.urls import path
from Resume import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='resume'), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Skills/urls.py
from django.urls import path
from Skills import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.ListView.as_view(template_name='skills/list.html'), name='skills'), 
    path('<int:pk>', views.DetailView.as_view(template_name='skills/item.html'), name='skill-detail'), 
]

Skills/models.py
from django.db import models
from django.contrib.auth.models import User 
from datetime import datetime
from django.template.defaultfilters import slugify
from django.urls import reverse 
from django.utils import timezone
from tinymce.models import HTMLField
from Projects.models import Project

class Skill(models.Model): 
    """
    Skill Object 
    """
    title = models.CharField(max_length=100)
    handle = models.SlugField(unique=True, blank=True)
    description = HTMLField(blank=True)
    image = models.ImageField(upload_to='collections/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    projects = models.ManyToManyField(Project)

    class Meta: 
        ordering = ['title']

    def __str__(self): 
        return self.title

    def save(self, *args, **kwargs): 
        self.slug = slugify(self.title)
        return super(Skill, self).save(*args, **kwargs)

Skills/views.py
import io 
from django.shortcuts import render
from Skills.models import Skill
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.conf import settings
# Returning PDFS 
from django.http import HttpResponseRedirect
 

class ListView(ListView):
    model = Skill

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DetailView(DetailView): 
    model = Skill
    print('test')
    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)
        return context

templates/skills/item.html
{% extends 'layout/app.html' %}
{% load static %}

{% block title%} <title>{{skill.title}}</title> {% endblock title%}

{%block body%}
    {% include 'sections/skill-description.html' %}
    {% include 'sections/works.html' with projects=skill.projects.all %}
{%endblock body%}

templates/skills/list.html
{%extends 'layout/app.html'%}
{%load static%}
{%block title%}
<title>Skills</title>
{%endblock title%}
{%block body%}
    <!-- Hero -->
    <header class="hero hero_decoration-points">
        <div class="carousel-vertical swiper-container">
            <div class="swiper-wrapper">
                {% for skill in skill_list %}
                    {% include 'sections/skill-list-item.html' with skill=skill %}
                {% endfor %}
            </div>
            
            <!-- Pagination -->
            <div class="swiper-pagination _bottom"></div>
                
            <!-- Control -->
            <div class="swiper-control swiper-control_bottom">
                <div class="swiper-button-next">Next</div>
                <div class="swiper-button-prev">Prev</div>
            </div>
        </div>
    </header>	
    <!-- /Hero -->
    {%include 'sections/footer.html'%}
{%endblock body%}